name: "Build Test"

on: workflow_dispatch

jobs:
  build-test:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-26" # for Arm based macs (M1 and above). Uses macOS 26 for Apple Intelligence SDK.
            args: "--target aarch64-apple-darwin --bundles app"
            target: "aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin --bundles app"
            target: "x86_64-apple-darwin"

    uses: ./.github/workflows/build.yml
    with:
      platform: ${{ matrix.platform }}
      target: ${{ matrix.target }}
      build-args: ${{ matrix.args }}
      sign-binaries: true
      asset-prefix: "ng-dictate-test"
      upload-artifacts: true
      is-debug-build: ${{ contains(matrix.args, '--debug') }}
    secrets: inherit
